DROP TABLE IF EXISTS ORDERR;
CREATE TABLE ORDERR(
ID INTEGER NOT NULL AUTO_INCREMENT,
TYPE VARCHAR(50) NOT NULL,
TOPPING VARCHAR(50) NOT NULL,
QUANTITY INT(8) NOT NULL
);
INSERT INTO ORDERR (TYPE,TOPPING,QUANTITY) VALUES ('type3', 'Capcicum', 5),('type4', 'chicken', 5);
